### ISSUE TITLE
Channel /StopPoint/Departures is broken

### ISSUE THREAD

**Issue by chasset** [TfLlu/TfL-API-Client#4]
Hello,

The API of mobiliteit.lu changes a few days ago.
It requires now to declare in the URL …&id=A=1@L=…
Thanks for your Streaming APIs,

Pierre-Olivier

**Comment by dattn** [comment]
We already used the new URL format, but ower "look_maxdist" param was to long. I reduced it to "99999999999" and now it works again.

mobiliteit.lu must have added some checks a few days ago, that limits the search distance.

**Comment by chasset** [comment]
Well done!
