### ISSUE TITLE
Streaming API is broken

### ISSUE THREAD

**Issue by chasset** [TfLlu/TfL-API-Client#7]
Hello,

Sadly, the fix for 'Departures' broke the live demo example.
It doesn't work anymore since this morning, neither my script to capture this flow.
Best regards,

Pierre-Olivier

**Comment by dattn** [comment]
I have released a new version "0.0.13". The demo works again.
Can you please update to the latest version and tell me if it is working for you ?

**Comment by chasset** [comment]
It works!
Many thanks
